apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: megastore-lol
spec:
  secretName: megastore-lol-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  dnsNames:
    - megastore.lol
    - www.megastore.lol

