apiVersion: v1
kind: Service
metadata:
  name: commerce-proxy
spec:
  type: ExternalName
  externalName: commerce.hanzo.svc.cluster.local
  ports:
    - name: http
      port: 8001
      targetPort: 8001
