apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: adxyz

resources:
  - ../../base
  - namespace.yaml
  - ingress.yaml

images:
  - name: ghcr.io/ad-xyz/mega-store
    newName: ghcr.io/ad-xyz/mega-store
    newTag: latest
